apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-publisher
  labels:
    app: rabbitmq-publisher
spec:
  selector:
    matchLabels:
      app: rabbitmq-publisher
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq-publisher
    spec:
      containers: 
      - name: rabbitmq-publisher
        image: ilthi96/rabbitpy-publisher:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000


# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: rabbitmq-publisher
#   labels:
#     app: rabbitmq-publisher
# spec:
#   type: LoadBalancer
#   selector:
#     app: rabbitmq-publisher
#   ports:
#     - protocol: TCP
#       name: http
#       port: 5000
#       targetPort: 80

