apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-consumer
type: Opaque
data:
  RABBIT_USERNAME: Z3Vlc3Q=
  RABBIT_PASSWORD: Z3Vlc3Q=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-consumer
  labels:
    app: rabbitmq-consumer
spec:
  selector:
    matchLabels:
      app: rabbitmq-consumer
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq-consumer
    spec:
      serviceAccountName: rabbitmq
      containers:
      - name: rabbitmq-consumer
        image: ilthi96/rabbitpy-consumer-topic:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: RABBIT_HOST
          value: "rabbitmq-0.rabbitmq.rabbits.svc.cluster.local"
        - name: RABBIT_PORT
          value: "5672"
        - name: RABBIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-consumer
              key: RABBIT_USERNAME
        - name: RABBIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-consumer
              key: RABBIT_PASSWORD
        volumeMounts:
          - name: config
            mountPath: "/config"
      volumes:
          - name: config
            configMap:
              name: "ci-config"  
      
       
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: rabbitmq-consumer
#   labels:
#     app: rabbitmq-consumer
# spec:
#   type: LoadBalancer
#   selector:
#     app: rabbitmq-consumer
#   ports:
#     - protocol: TCP
#       name: http
#       port: 80
#       targetPort: 80
